-- Set DDL

-- Warehouses
CREATE OR ALTER WAREHOUSE TEST_WH 
    WAREHOUSE_SIZE = XSMALL, 
    AUTO_SUSPEND = 300, 
    AUTO_RESUME= TRUE;
USE WAREHOUSE TEST_WH;


-- Databases
CREATE OR ALTER DATABASE DEVOPS_WITH_SNOWFLAKE_DEV;
CREATE OR ALTER DATABASE DEVOPS_WITH_SNOWFLAKE_PROD;
USE DATABASE DEVOPS_WITH_SNOWFLAKE_DEV;

-- Schemas
CREATE OR ALTER SCHEMA INTEGRATIONS;
CREATE OR ALTER SCHEMA BRONZE;
CREATE OR ALTER SCHEMA SILVER;
CREATE OR ALTER SCHEMA GOLD;

-- Stages
CREATE OR ALTER STAGE BRONZE.RAW;

-- File Formats
CREATE OR REPLACE FILE FORMAT BRONZE.json_format 
    TYPE = 'json';

-- DevOps
CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_INTERGRATION
  TYPE=EMAIL
  ENABLED=TRUE;

-- GITHUB Variables
SET GITHUB_URL = 'https://github.com';
SET GITHUB_USERNAME = 'ncarlson-mhnchicago';  -- TODO!!!
SET GITHUB_REPO = 'dev_ops_with_snowflake';
SET GITHUB_URL_PREFIX = $GITHUB_URL || '/' || $GITHUB_USERNAME;
SET GITHUB_REPO_ORIGIN = $GITHUB_URL || '/' || $GITHUB_USERNAME || '/' || $GITHUB_REPO || '.git';

USE SCHEMA INTEGRATIONS;
-- API Integration (account level)
CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ($GITHUB_URL_PREFIX)
  ALLOWED_AUTHENTICATION_SECRETS = (ENV_DB.DEV.GITHUB_SECRET)
  ENABLED = TRUE;

-- Git Repository
CREATE OR REPLACE GIT REPOSITORY GITHUB_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = ENV_DB.DEV.GITHUB_SECRET
  ORIGIN = $GITHUB_REPO_ORIGIN;


SHOW API INTEGRATIONS;

SHOW GIT REPOSITORIES;



-- -- Copy file from GitHub to internal stage
-- COPY FILES INTO @BRONZE.RAW FROM @DEVOPS_WITH_SNOWFLAKE_DEV.INTEGRATIONS.GITHUB_REPO/branches/main/data/airport_list.json;
